#!/bin/bash


# Running PIQ en mass

# Prep the bam, only need to be done once for each set of bam replicates

# $1 is the output folder
# $2 is input bam file replicate 1
# $3 is input bam file replicate 2

Rscript bam2rdata.hofstenia.r common.hofstenia.r $1/d0.Rdata $2 $3
---------------------------------------------------------------------------------------------------------------------------

# Motif matching on the genome (only need to do once, used jaspar.txt)

Rscript pwmmatch.exact.r common.hofstenia.r jaspar.txt $ARRAY_TASK_ID motif_match_files blacklist.bed
---------------------------------------------------------------------------------------------------------------------------
# all of the motif match files are placed into the folder "motif_match_files"

# to combine the motif match scores with ONE of the prepped bams:

# be careful about the time requested, could need > 24 hours

MOTIFFOLDER=$1 #first argument to script
BAMFOLDER=$2 #second argument to script

TMPDIR=/scratch/piq_run_$SLURM_ARRAY_TASK_ID
mkdir -p $TMPDIR

OUTPUT=/net/fs2k02/srv/export/srivastava_lab/share_root/Andrew_Gehrke/PIQ/results_$BAMFOLDER/pwm$SLURM_ARRAY_TASK_ID
mkdir -p $OUTPUT

PWM=$SLURM_ARRAY_TASK_ID

# Run the R script
Rscript pertf.chromdump.r common.hofstenia.r \
$MOTIFFOLDER \
$TMPDIR \
$OUTPUT \
$BAMFOLDER/d0.Rdata $PWM

#--//
---------------------------------------------------------------------------------------------------------------------------
# recover pioneer factor scores

$ mkdir pioneer_index_scores

$ cd results_6h_prepped_bam_FINAL/

$ find . -name '*\ *.txt' -exec cp {} /net/fs2k02/srv/export/srivastava_lab/share_root/Andrew_Gehrke/PIQ/pioneer_index_scores/ \;

$ ..

$ cd pioneer_index_scores/

$ cat *\ *.txt > pioneer_scores_master.txt
