#!/bin/bash

# Running Salmon

salmon quant -i <salmon_index> --numBootstraps 100 -l A -r <single_end_reads>.fastq -p 4 -o  <reads>_salmon_output_FINAL

----------------------------------------------------------------------------------------------------------
# DE with sleuth

#reminder: salmon has to be run with bootstraps in order to be converted to kallisto format

#convert salmon output to kallisto format.  Each file listed here is folder straight from salmon output, with a .sf file inside
> sfdirs <-  c("0h_rep1_tail/", "0h_rep2_tail/","0h_rep3_tail/","1h_rep1_tail/","1h_rep2_tail/","1h_rep3_tail/","3h_rep1_tail/","3h_rep2_tail/","3h_rep3_tail/","6h_rep1_tail/","6h_rep2_tail/","6h_rep3_tail/","12h_rep1_tail/","12h_rep2_tail/","12h_rep3_tail/")

> prepare_fish_for_sleuth(sfdirs)

> sample_id <- dir(file.path("/Users/agehrke/desktop/ATAC_final_files/clean_final_files/bam_master_folder/wasabi/"))

> kal_dirs <- file.path("/Users/agehrke/desktop/ATAC_final_files/clean_final_files/bam_master_folder/wasabi/", sample_id)

#move s2c.csv file into folder before running this command
> s2c<-read.table("/Users/agehrke/desktop/ATAC_final_files/clean_final_files/bam_master_folder/wasabi/dme_elev_samples.csv",header = TRUE, stringsAsFactors=FALSE)

> s2c <- mutate(s2c, path = kal_dirs)

> library(sleuth)

> so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE,read_bootstrap_tpm=TRUE)

> so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE,read_bootstrap_tpm=TRUE)

> so <- sleuth_fit(so, ~condition, 'full')

> so <- sleuth_fit(so, ~1, 'reduced')

> so <- sleuth_lrt(so, 'reduced', 'full')

> sleuth_table <- sleuth_results(so, 'reduced:full', 'lrt', show_all = TRUE)

> temphigh<-s2c$sample[s2c$condition=="0h"]
> templow<-s2c$sample[s2c$condition=="1h"]
> hiraw<-subset(so$obs_raw,so$obs_raw$sample %in% temphigh)
> lowraw<-subset(so$obs_raw,so$obs_raw$sample %in% templow)
> highmeans<-aggregate(tpm~target_id,data=hiraw,FUN=function(x) c(mean=mean(x)))
> colnames(highmeans)<-c("target_id","tpm_high")
> lowmeans<-aggregate(tpm~target_id,data=lowraw,FUN=function(x) c(mean=mean(x)))
> colnames(lowmeans)<-c("target_id","tpm_low")
> merged_means<-merge(lowmeans,highmeans,by=c("target_id"))
> sleuth_table_wTPM<-left_join(sleuth_table,merged_means)

> write.csv(sleuth_table_wTPM, "sleuth_0v1_wTMP_FINAL.csv")
